name: build

on:
    push:
      branches-ignore: [ 'main' ]
      paths: [ '.github/workflows/build.yml', '*.bat', 'ci/build.py', 'cmake/**', 'onnxruntime/**', 'tools/**' ]
    pull_request:
      paths: [ '.github/workflows/build.yml', '*.bat', 'ci/build.py', 'cmake/**', 'onnxruntime/**', 'tools/**' ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: ['x64', 'ARM64']

    steps:
    - uses: actions/checkout@v4

    - name: Set up PATH
      # Needed to use GNU patch instead of Strawberry Perl patch
      run: echo "C:\Program Files\Git\usr\bin" >> $env:GITHUB_PATH

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Requests
      run: pip install requests

    - name: Build
      run: python ci/build.py ${{ matrix.platform }}

    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with: 
          name: onnxruntime-${{ matrix.platform }}
          path: build/Release/Release
